package com.madhouse.platform.premiummad.entity;

import java.util.Date;

public class Advertiser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.id
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.dsp_id
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private Integer dspId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.advertiser_key
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private String advertiserKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.advertiser_name
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private String advertiserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.media_id
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private Integer mediaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.industry
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private Short industry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.website
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private String website;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.contact
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.address
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.phone
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.license
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private String license;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.status
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.reason
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.media_advertiser_key
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private String mediaAdvertiserKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.audited_user
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private Integer auditedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.created_time
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser.updated_time
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	private Date updatedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.id
	 * @return  the value of mad_sys_advertiser.id
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.id
	 * @param id  the value for mad_sys_advertiser.id
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.dsp_id
	 * @return  the value of mad_sys_advertiser.dsp_id
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public Integer getDspId() {
		return dspId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.dsp_id
	 * @param dspId  the value for mad_sys_advertiser.dsp_id
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setDspId(Integer dspId) {
		this.dspId = dspId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.advertiser_key
	 * @return  the value of mad_sys_advertiser.advertiser_key
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public String getAdvertiserKey() {
		return advertiserKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.advertiser_key
	 * @param advertiserKey  the value for mad_sys_advertiser.advertiser_key
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setAdvertiserKey(String advertiserKey) {
		this.advertiserKey = advertiserKey == null ? null : advertiserKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.advertiser_name
	 * @return  the value of mad_sys_advertiser.advertiser_name
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public String getAdvertiserName() {
		return advertiserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.advertiser_name
	 * @param advertiserName  the value for mad_sys_advertiser.advertiser_name
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setAdvertiserName(String advertiserName) {
		this.advertiserName = advertiserName == null ? null : advertiserName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.media_id
	 * @return  the value of mad_sys_advertiser.media_id
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public Integer getMediaId() {
		return mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.media_id
	 * @param mediaId  the value for mad_sys_advertiser.media_id
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setMediaId(Integer mediaId) {
		this.mediaId = mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.industry
	 * @return  the value of mad_sys_advertiser.industry
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public Short getIndustry() {
		return industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.industry
	 * @param industry  the value for mad_sys_advertiser.industry
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setIndustry(Short industry) {
		this.industry = industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.website
	 * @return  the value of mad_sys_advertiser.website
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.website
	 * @param website  the value for mad_sys_advertiser.website
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setWebsite(String website) {
		this.website = website == null ? null : website.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.contact
	 * @return  the value of mad_sys_advertiser.contact
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.contact
	 * @param contact  the value for mad_sys_advertiser.contact
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setContact(String contact) {
		this.contact = contact == null ? null : contact.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.address
	 * @return  the value of mad_sys_advertiser.address
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.address
	 * @param address  the value for mad_sys_advertiser.address
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.phone
	 * @return  the value of mad_sys_advertiser.phone
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.phone
	 * @param phone  the value for mad_sys_advertiser.phone
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.license
	 * @return  the value of mad_sys_advertiser.license
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public String getLicense() {
		return license;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.license
	 * @param license  the value for mad_sys_advertiser.license
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setLicense(String license) {
		this.license = license == null ? null : license.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.status
	 * @return  the value of mad_sys_advertiser.status
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.status
	 * @param status  the value for mad_sys_advertiser.status
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.reason
	 * @return  the value of mad_sys_advertiser.reason
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.reason
	 * @param reason  the value for mad_sys_advertiser.reason
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.media_advertiser_key
	 * @return  the value of mad_sys_advertiser.media_advertiser_key
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public String getMediaAdvertiserKey() {
		return mediaAdvertiserKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.media_advertiser_key
	 * @param mediaAdvertiserKey  the value for mad_sys_advertiser.media_advertiser_key
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setMediaAdvertiserKey(String mediaAdvertiserKey) {
		this.mediaAdvertiserKey = mediaAdvertiserKey == null ? null : mediaAdvertiserKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.audited_user
	 * @return  the value of mad_sys_advertiser.audited_user
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public Integer getAuditedUser() {
		return auditedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.audited_user
	 * @param auditedUser  the value for mad_sys_advertiser.audited_user
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setAuditedUser(Integer auditedUser) {
		this.auditedUser = auditedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.created_time
	 * @return  the value of mad_sys_advertiser.created_time
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.created_time
	 * @param createdTime  the value for mad_sys_advertiser.created_time
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser.updated_time
	 * @return  the value of mad_sys_advertiser.updated_time
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser.updated_time
	 * @param updatedTime  the value for mad_sys_advertiser.updated_time
	 * @mbggenerated  Wed Jul 26 10:30:28 CST 2017
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}
}