package com.madhouse.platform.premiummad.entity;

import java.util.Date;

public class AdvertiserUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser_user.id
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser_user.advertiser_id
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	private Integer advertiserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser_user.user_id
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser_user.status
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser_user.reason
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser_user.created_time
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_advertiser_user.updated_time
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	private Date updatedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser_user.id
	 * @return  the value of mad_sys_advertiser_user.id
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser_user.id
	 * @param id  the value for mad_sys_advertiser_user.id
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser_user.advertiser_id
	 * @return  the value of mad_sys_advertiser_user.advertiser_id
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public Integer getAdvertiserId() {
		return advertiserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser_user.advertiser_id
	 * @param advertiserId  the value for mad_sys_advertiser_user.advertiser_id
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public void setAdvertiserId(Integer advertiserId) {
		this.advertiserId = advertiserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser_user.user_id
	 * @return  the value of mad_sys_advertiser_user.user_id
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser_user.user_id
	 * @param userId  the value for mad_sys_advertiser_user.user_id
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser_user.status
	 * @return  the value of mad_sys_advertiser_user.status
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser_user.status
	 * @param status  the value for mad_sys_advertiser_user.status
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser_user.reason
	 * @return  the value of mad_sys_advertiser_user.reason
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser_user.reason
	 * @param reason  the value for mad_sys_advertiser_user.reason
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser_user.created_time
	 * @return  the value of mad_sys_advertiser_user.created_time
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser_user.created_time
	 * @param createdTime  the value for mad_sys_advertiser_user.created_time
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_advertiser_user.updated_time
	 * @return  the value of mad_sys_advertiser_user.updated_time
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_advertiser_user.updated_time
	 * @param updatedTime  the value for mad_sys_advertiser_user.updated_time
	 * @mbggenerated  Mon Dec 25 15:21:17 CST 2017
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}
}