package com.madhouse.platform.premiummad.entity;

public class Dsp extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_dsp.id
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_dsp.name
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_dsp.bid_url
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    private String bidUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_dsp.winnotice_url
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    private String winnoticeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_dsp.delivery_type
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    private Byte deliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_dsp.bid_percent
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    private Integer bidPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_dsp.token
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_dsp.status
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_dsp.max_qps
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    private Integer maxQPS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_dsp.id
     *
     * @return the value of mad_sys_dsp.id
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_dsp.id
     *
     * @param id the value for mad_sys_dsp.id
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_dsp.name
     *
     * @return the value of mad_sys_dsp.name
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_dsp.name
     *
     * @param name the value for mad_sys_dsp.name
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_dsp.bid_url
     *
     * @return the value of mad_sys_dsp.bid_url
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public String getBidUrl() {
        return bidUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_dsp.bid_url
     *
     * @param bidUrl the value for mad_sys_dsp.bid_url
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public void setBidUrl(String bidUrl) {
        this.bidUrl = bidUrl == null ? null : bidUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_dsp.winnotice_url
     *
     * @return the value of mad_sys_dsp.winnotice_url
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public String getWinnoticeUrl() {
        return winnoticeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_dsp.winnotice_url
     *
     * @param winnoticeUrl the value for mad_sys_dsp.winnotice_url
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public void setWinnoticeUrl(String winnoticeUrl) {
        this.winnoticeUrl = winnoticeUrl == null ? null : winnoticeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_dsp.delivery_type
     *
     * @return the value of mad_sys_dsp.delivery_type
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public Byte getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_dsp.delivery_type
     *
     * @param deliveryType the value for mad_sys_dsp.delivery_type
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public void setDeliveryType(Byte deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_dsp.bid_percent
     *
     * @return the value of mad_sys_dsp.bid_percent
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public Integer getBidPercent() {
        return bidPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_dsp.bid_percent
     *
     * @param bidPercent the value for mad_sys_dsp.bid_percent
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public void setBidPercent(Integer bidPercent) {
        this.bidPercent = bidPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_dsp.token
     *
     * @return the value of mad_sys_dsp.token
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_dsp.token
     *
     * @param token the value for mad_sys_dsp.token
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_dsp.status
     *
     * @return the value of mad_sys_dsp.status
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_dsp.status
     *
     * @param status the value for mad_sys_dsp.status
     *
     * @mbggenerated Mon Jul 17 12:07:44 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Integer getMaxQPS() {
		return maxQPS;
	}

	public void setMaxQPS(Integer maxQPS) {
		this.maxQPS = maxQPS;
	}
}