package com.madhouse.platform.premiummad.entity;

import java.util.Date;

public class DspMedia {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_dsp_media.id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_dsp_media.dsp_id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	private Integer dspId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_dsp_media.media_id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	private Integer mediaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_dsp_media.adspace_id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	private Integer adspaceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_dsp_media.created_user
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	private Integer createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_dsp_media.created_time
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	private Date createdTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_dsp_media.id
	 * @return  the value of mad_sys_dsp_media.id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_dsp_media.id
	 * @param id  the value for mad_sys_dsp_media.id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_dsp_media.dsp_id
	 * @return  the value of mad_sys_dsp_media.dsp_id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public Integer getDspId() {
		return dspId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_dsp_media.dsp_id
	 * @param dspId  the value for mad_sys_dsp_media.dsp_id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public void setDspId(Integer dspId) {
		this.dspId = dspId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_dsp_media.media_id
	 * @return  the value of mad_sys_dsp_media.media_id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public Integer getMediaId() {
		return mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_dsp_media.media_id
	 * @param mediaId  the value for mad_sys_dsp_media.media_id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public void setMediaId(Integer mediaId) {
		this.mediaId = mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_dsp_media.adspace_id
	 * @return  the value of mad_sys_dsp_media.adspace_id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public Integer getAdspaceId() {
		return adspaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_dsp_media.adspace_id
	 * @param adspaceId  the value for mad_sys_dsp_media.adspace_id
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public void setAdspaceId(Integer adspaceId) {
		this.adspaceId = adspaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_dsp_media.created_user
	 * @return  the value of mad_sys_dsp_media.created_user
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public Integer getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_dsp_media.created_user
	 * @param createdUser  the value for mad_sys_dsp_media.created_user
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public void setCreatedUser(Integer createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_dsp_media.created_time
	 * @return  the value of mad_sys_dsp_media.created_time
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_dsp_media.created_time
	 * @param createdTime  the value for mad_sys_dsp_media.created_time
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}
}