package com.madhouse.platform.premiummad.entity;

public class Location {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_dict_location.id
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_dict_location.level
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_dict_location.parent_code
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_dict_location.code
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_dict_location.name
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_dict_location.domestic
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    private Integer domestic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_dict_location.id
     *
     * @return the value of mad_dict_location.id
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_dict_location.id
     *
     * @param id the value for mad_dict_location.id
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_dict_location.level
     *
     * @return the value of mad_dict_location.level
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_dict_location.level
     *
     * @param level the value for mad_dict_location.level
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_dict_location.parent_code
     *
     * @return the value of mad_dict_location.parent_code
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_dict_location.parent_code
     *
     * @param parentCode the value for mad_dict_location.parent_code
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_dict_location.code
     *
     * @return the value of mad_dict_location.code
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_dict_location.code
     *
     * @param code the value for mad_dict_location.code
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_dict_location.name
     *
     * @return the value of mad_dict_location.name
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_dict_location.name
     *
     * @param name the value for mad_dict_location.name
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_dict_location.domestic
     *
     * @return the value of mad_dict_location.domestic
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public Integer getDomestic() {
        return domestic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_dict_location.domestic
     *
     * @param domestic the value for mad_dict_location.domestic
     *
     * @mbggenerated Wed Jul 26 13:52:54 CST 2017
     */
    public void setDomestic(Integer domestic) {
        this.domestic = domestic;
    }
}