package com.madhouse.platform.premiummad.entity;

import java.util.Date;

public class MaterialMedia {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material_media.id
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material_media.material_id
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	private Integer materialId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material_media.media_id
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	private Integer mediaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material_media.auditee
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	private Boolean auditee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material_media.status
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material_media.reason
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material_media.created_time
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material_media.audited_user
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	private Integer auditedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material_media.audited_time
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	private Date auditedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material_media.id
	 * @return  the value of mad_sys_material_media.id
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material_media.id
	 * @param id  the value for mad_sys_material_media.id
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material_media.material_id
	 * @return  the value of mad_sys_material_media.material_id
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public Integer getMaterialId() {
		return materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material_media.material_id
	 * @param materialId  the value for mad_sys_material_media.material_id
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public void setMaterialId(Integer materialId) {
		this.materialId = materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material_media.media_id
	 * @return  the value of mad_sys_material_media.media_id
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public Integer getMediaId() {
		return mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material_media.media_id
	 * @param mediaId  the value for mad_sys_material_media.media_id
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public void setMediaId(Integer mediaId) {
		this.mediaId = mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material_media.auditee
	 * @return  the value of mad_sys_material_media.auditee
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public Boolean getAuditee() {
		return auditee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material_media.auditee
	 * @param auditee  the value for mad_sys_material_media.auditee
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public void setAuditee(Boolean auditee) {
		this.auditee = auditee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material_media.status
	 * @return  the value of mad_sys_material_media.status
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material_media.status
	 * @param status  the value for mad_sys_material_media.status
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material_media.reason
	 * @return  the value of mad_sys_material_media.reason
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material_media.reason
	 * @param reason  the value for mad_sys_material_media.reason
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material_media.created_time
	 * @return  the value of mad_sys_material_media.created_time
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material_media.created_time
	 * @param createdTime  the value for mad_sys_material_media.created_time
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material_media.audited_user
	 * @return  the value of mad_sys_material_media.audited_user
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public Integer getAuditedUser() {
		return auditedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material_media.audited_user
	 * @param auditedUser  the value for mad_sys_material_media.audited_user
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public void setAuditedUser(Integer auditedUser) {
		this.auditedUser = auditedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material_media.audited_time
	 * @return  the value of mad_sys_material_media.audited_time
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public Date getAuditedTime() {
		return auditedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material_media.audited_time
	 * @param auditedTime  the value for mad_sys_material_media.audited_time
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	public void setAuditedTime(Date auditedTime) {
		this.auditedTime = auditedTime;
	}
}