package com.madhouse.platform.premiummad.entity;

import java.util.Date;

public class Material{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.dsp_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Integer dspId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.material_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String materialKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.material_name
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String materialName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.advertiser_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String advertiserKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.layout
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Short layout;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.media_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Integer mediaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.adspace_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Integer adspaceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.delivery_type
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Byte deliveryType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.brand
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String brand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.agency
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String agency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.deal_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Integer dealId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.start_date
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.end_date
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.size
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String size;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.icon
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.title
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.description
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.content
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.cover
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String cover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.ad_materials
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String adMaterials;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.duration
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Integer duration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.lpg_url
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String lpgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.active_type
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Byte activeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.imp_urls
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String impUrls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.clk_urls
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String clkUrls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.sec_urls
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String secUrls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.audited_user
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Integer auditedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.status
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.reason
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.media_query_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String mediaQueryKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.media_material_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String mediaMaterialKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.media_material_url
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private String mediaMaterialUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.created_time
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_material.updated_time
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	private Date updatedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.id
	 * @return  the value of mad_sys_material.id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.id
	 * @param id  the value for mad_sys_material.id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.dsp_id
	 * @return  the value of mad_sys_material.dsp_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Integer getDspId() {
		return dspId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.dsp_id
	 * @param dspId  the value for mad_sys_material.dsp_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setDspId(Integer dspId) {
		this.dspId = dspId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.material_key
	 * @return  the value of mad_sys_material.material_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getMaterialKey() {
		return materialKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.material_key
	 * @param materialKey  the value for mad_sys_material.material_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setMaterialKey(String materialKey) {
		this.materialKey = materialKey == null ? null : materialKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.material_name
	 * @return  the value of mad_sys_material.material_name
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getMaterialName() {
		return materialName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.material_name
	 * @param materialName  the value for mad_sys_material.material_name
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setMaterialName(String materialName) {
		this.materialName = materialName == null ? null : materialName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.advertiser_key
	 * @return  the value of mad_sys_material.advertiser_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getAdvertiserKey() {
		return advertiserKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.advertiser_key
	 * @param advertiserKey  the value for mad_sys_material.advertiser_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setAdvertiserKey(String advertiserKey) {
		this.advertiserKey = advertiserKey == null ? null : advertiserKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.layout
	 * @return  the value of mad_sys_material.layout
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Short getLayout() {
		return layout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.layout
	 * @param layout  the value for mad_sys_material.layout
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setLayout(Short layout) {
		this.layout = layout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.media_id
	 * @return  the value of mad_sys_material.media_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Integer getMediaId() {
		return mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.media_id
	 * @param mediaId  the value for mad_sys_material.media_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setMediaId(Integer mediaId) {
		this.mediaId = mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.adspace_id
	 * @return  the value of mad_sys_material.adspace_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Integer getAdspaceId() {
		return adspaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.adspace_id
	 * @param adspaceId  the value for mad_sys_material.adspace_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setAdspaceId(Integer adspaceId) {
		this.adspaceId = adspaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.delivery_type
	 * @return  the value of mad_sys_material.delivery_type
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Byte getDeliveryType() {
		return deliveryType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.delivery_type
	 * @param deliveryType  the value for mad_sys_material.delivery_type
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setDeliveryType(Byte deliveryType) {
		this.deliveryType = deliveryType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.brand
	 * @return  the value of mad_sys_material.brand
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.brand
	 * @param brand  the value for mad_sys_material.brand
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setBrand(String brand) {
		this.brand = brand == null ? null : brand.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.agency
	 * @return  the value of mad_sys_material.agency
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getAgency() {
		return agency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.agency
	 * @param agency  the value for mad_sys_material.agency
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setAgency(String agency) {
		this.agency = agency == null ? null : agency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.deal_id
	 * @return  the value of mad_sys_material.deal_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Integer getDealId() {
		return dealId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.deal_id
	 * @param dealId  the value for mad_sys_material.deal_id
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setDealId(Integer dealId) {
		this.dealId = dealId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.start_date
	 * @return  the value of mad_sys_material.start_date
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.start_date
	 * @param startDate  the value for mad_sys_material.start_date
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.end_date
	 * @return  the value of mad_sys_material.end_date
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.end_date
	 * @param endDate  the value for mad_sys_material.end_date
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.size
	 * @return  the value of mad_sys_material.size
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.size
	 * @param size  the value for mad_sys_material.size
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setSize(String size) {
		this.size = size == null ? null : size.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.icon
	 * @return  the value of mad_sys_material.icon
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.icon
	 * @param icon  the value for mad_sys_material.icon
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setIcon(String icon) {
		this.icon = icon == null ? null : icon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.title
	 * @return  the value of mad_sys_material.title
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.title
	 * @param title  the value for mad_sys_material.title
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.description
	 * @return  the value of mad_sys_material.description
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.description
	 * @param description  the value for mad_sys_material.description
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.content
	 * @return  the value of mad_sys_material.content
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.content
	 * @param content  the value for mad_sys_material.content
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.cover
	 * @return  the value of mad_sys_material.cover
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getCover() {
		return cover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.cover
	 * @param cover  the value for mad_sys_material.cover
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setCover(String cover) {
		this.cover = cover == null ? null : cover.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.ad_materials
	 * @return  the value of mad_sys_material.ad_materials
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getAdMaterials() {
		return adMaterials;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.ad_materials
	 * @param adMaterials  the value for mad_sys_material.ad_materials
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setAdMaterials(String adMaterials) {
		this.adMaterials = adMaterials == null ? null : adMaterials.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.duration
	 * @return  the value of mad_sys_material.duration
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Integer getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.duration
	 * @param duration  the value for mad_sys_material.duration
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.lpg_url
	 * @return  the value of mad_sys_material.lpg_url
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getLpgUrl() {
		return lpgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.lpg_url
	 * @param lpgUrl  the value for mad_sys_material.lpg_url
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setLpgUrl(String lpgUrl) {
		this.lpgUrl = lpgUrl == null ? null : lpgUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.active_type
	 * @return  the value of mad_sys_material.active_type
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Byte getActiveType() {
		return activeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.active_type
	 * @param activeType  the value for mad_sys_material.active_type
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setActiveType(Byte activeType) {
		this.activeType = activeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.imp_urls
	 * @return  the value of mad_sys_material.imp_urls
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getImpUrls() {
		return impUrls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.imp_urls
	 * @param impUrls  the value for mad_sys_material.imp_urls
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setImpUrls(String impUrls) {
		this.impUrls = impUrls == null ? null : impUrls.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.clk_urls
	 * @return  the value of mad_sys_material.clk_urls
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getClkUrls() {
		return clkUrls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.clk_urls
	 * @param clkUrls  the value for mad_sys_material.clk_urls
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setClkUrls(String clkUrls) {
		this.clkUrls = clkUrls == null ? null : clkUrls.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.sec_urls
	 * @return  the value of mad_sys_material.sec_urls
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getSecUrls() {
		return secUrls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.sec_urls
	 * @param secUrls  the value for mad_sys_material.sec_urls
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setSecUrls(String secUrls) {
		this.secUrls = secUrls == null ? null : secUrls.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.audited_user
	 * @return  the value of mad_sys_material.audited_user
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Integer getAuditedUser() {
		return auditedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.audited_user
	 * @param auditedUser  the value for mad_sys_material.audited_user
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setAuditedUser(Integer auditedUser) {
		this.auditedUser = auditedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.status
	 * @return  the value of mad_sys_material.status
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.status
	 * @param status  the value for mad_sys_material.status
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.reason
	 * @return  the value of mad_sys_material.reason
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.reason
	 * @param reason  the value for mad_sys_material.reason
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setReason(String reason) {
		this.reason = reason == null ? null : reason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.media_query_key
	 * @return  the value of mad_sys_material.media_query_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getMediaQueryKey() {
		return mediaQueryKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.media_query_key
	 * @param mediaQueryKey  the value for mad_sys_material.media_query_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setMediaQueryKey(String mediaQueryKey) {
		this.mediaQueryKey = mediaQueryKey == null ? null : mediaQueryKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.media_material_key
	 * @return  the value of mad_sys_material.media_material_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getMediaMaterialKey() {
		return mediaMaterialKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.media_material_key
	 * @param mediaMaterialKey  the value for mad_sys_material.media_material_key
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setMediaMaterialKey(String mediaMaterialKey) {
		this.mediaMaterialKey = mediaMaterialKey == null ? null : mediaMaterialKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.media_material_url
	 * @return  the value of mad_sys_material.media_material_url
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public String getMediaMaterialUrl() {
		return mediaMaterialUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.media_material_url
	 * @param mediaMaterialUrl  the value for mad_sys_material.media_material_url
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setMediaMaterialUrl(String mediaMaterialUrl) {
		this.mediaMaterialUrl = mediaMaterialUrl == null ? null : mediaMaterialUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.created_time
	 * @return  the value of mad_sys_material.created_time
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.created_time
	 * @param createdTime  the value for mad_sys_material.created_time
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_material.updated_time
	 * @return  the value of mad_sys_material.updated_time
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_material.updated_time
	 * @param updatedTime  the value for mad_sys_material.updated_time
	 * @mbggenerated  Fri Sep 01 11:39:46 CST 2017
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	private String dspName;
	private String advertiserName;
	private Integer materialLayout;
	private String mediaName;
	
	private Integer materialAuditMode;
	
	public String getDspName() {
		return dspName;
	}

	public void setDspName(String dspName) {
		this.dspName = dspName;
	}

	public String getAdvertiserName() {
		return advertiserName;
	}

	public void setAdvertiserName(String advertiserName) {
		this.advertiserName = advertiserName;
	}

	public Integer getMaterialLayout() {
		return materialLayout;
	}

	public void setMaterialLayout(Integer materialLayout) {
		this.materialLayout = materialLayout;
	}

	public String getMediaName() {
		return mediaName;
	}

	public void setMediaName(String mediaName) {
		this.mediaName = mediaName;
	}

	public Integer getMaterialAuditMode() {
		return materialAuditMode;
	}

	public void setMaterialAuditMode(Integer materialAuditMode) {
		this.materialAuditMode = materialAuditMode;
	}

}