package com.madhouse.platform.premiummad.entity;

import java.util.Date;
import java.util.List;

public class Policy extends BaseEntity{
	
	private Integer id;
	
	private Integer dealId;

    private String name;
    
    private Integer type; //策略类型(1: PDB, 2: PD, 4: PMP, 8: RTB)
    
    private Integer weight; //权重
    
    private Date startDate;
    
    private Date endDate;
    
    private String timeTargeting; //时间定向(格式:0:0,1,2,3&1:19,20,21,22,23)

    private String locationTargeting; //地域定向

    private String osTargeting; //OS定向(多个用半角逗号分隔, 1:Android, 2:iOS, 3: 其它)

    private String connTargeting; //连网方式定向(多个用半角逗号分隔, 1:WIFI, 2:2G, 3:3G, 4:4G)

    private Byte limitType; //总量控制(0: 不限, 1: 每天, 2: 整单)

    private Integer limitReqs;

    private Byte limitSpeed; //投放速度(1:加速投放, 2:匀速投放)
    
    private Integer pushRatio; //流量返还比（大于100的整数，为返还流量点数 + 购买流量）

    private Byte status;

    private String description;
    
    private List<PolicyAdspace> policyAdspaces;
    
    private List<PolicyDsp> policyDsps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.id
     *
     * @return the value of mad_sys_policy.id
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.id
     *
     * @param id the value for mad_sys_policy.id
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.name
     *
     * @return the value of mad_sys_policy.name
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.name
     *
     * @param name the value for mad_sys_policy.name
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.type
     *
     * @return the value of mad_sys_policy.type
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.type
     *
     * @param type the value for mad_sys_policy.type
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getWeight() {
		return weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public Byte getLimitSpeed() {
		return limitSpeed;
	}

	public void setLimitSpeed(Byte limitSpeed) {
		this.limitSpeed = limitSpeed;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.start_date
     *
     * @return the value of mad_sys_policy.start_date
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.start_date
     *
     * @param startDate the value for mad_sys_policy.start_date
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.end_date
     *
     * @return the value of mad_sys_policy.end_date
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.end_date
     *
     * @param endDate the value for mad_sys_policy.end_date
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.time_targeting
     *
     * @return the value of mad_sys_policy.time_targeting
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public String getTimeTargeting() {
        return timeTargeting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.time_targeting
     *
     * @param timeTargeting the value for mad_sys_policy.time_targeting
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setTimeTargeting(String timeTargeting) {
        this.timeTargeting = timeTargeting == null ? null : timeTargeting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.location_targeting
     *
     * @return the value of mad_sys_policy.location_targeting
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public String getLocationTargeting() {
        return locationTargeting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.location_targeting
     *
     * @param locationTargeting the value for mad_sys_policy.location_targeting
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setLocationTargeting(String locationTargeting) {
        this.locationTargeting = locationTargeting == null ? null : locationTargeting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.os_targeting
     *
     * @return the value of mad_sys_policy.os_targeting
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public String getOsTargeting() {
        return osTargeting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.os_targeting
     *
     * @param osTargeting the value for mad_sys_policy.os_targeting
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setOsTargeting(String osTargeting) {
        this.osTargeting = osTargeting == null ? null : osTargeting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.conn_targeting
     *
     * @return the value of mad_sys_policy.conn_targeting
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public String getConnTargeting() {
        return connTargeting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.conn_targeting
     *
     * @param connTargeting the value for mad_sys_policy.conn_targeting
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setConnTargeting(String connTargeting) {
        this.connTargeting = connTargeting == null ? null : connTargeting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.limit_type
     *
     * @return the value of mad_sys_policy.limit_type
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public Byte getLimitType() {
        return limitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.limit_type
     *
     * @param limitType the value for mad_sys_policy.limit_type
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setLimitType(Byte limitType) {
        this.limitType = limitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.limit_reqs
     *
     * @return the value of mad_sys_policy.limit_reqs
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public Integer getLimitReqs() {
        return limitReqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.limit_reqs
     *
     * @param limitReqs the value for mad_sys_policy.limit_reqs
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setLimitReqs(Integer limitReqs) {
        this.limitReqs = limitReqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.status
     *
     * @return the value of mad_sys_policy.status
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.status
     *
     * @param status the value for mad_sys_policy.status
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy.description
     *
     * @return the value of mad_sys_policy.description
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy.description
     *
     * @param description the value for mad_sys_policy.description
     *
     * @mbggenerated Wed Jul 19 11:37:35 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	public List<PolicyAdspace> getPolicyAdspaces() {
		return policyAdspaces;
	}

	public void setPolicyAdspaces(List<PolicyAdspace> policyAdspaces) {
		this.policyAdspaces = policyAdspaces;
	}

	public List<PolicyDsp> getPolicyDsps() {
		return policyDsps;
	}

	public void setPolicyDsps(List<PolicyDsp> policyDsps) {
		this.policyDsps = policyDsps;
	}

	public Integer getDealId() {
		return dealId;
	}

	public void setDealId(Integer dealId) {
		this.dealId = dealId;
	}

	public Integer getPushRatio() {
		return pushRatio;
	}

	public void setPushRatio(Integer pushRatio) {
		this.pushRatio = pushRatio;
	}

}