package com.madhouse.platform.premiummad.entity;

import java.util.Date;

public class PolicyDsp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_policy_dsp.id
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_policy_dsp.policy_id
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    private Integer policyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_policy_dsp.dsp_id
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    private Integer dspId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_policy_dsp.weight
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    private Short weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_policy_dsp.status
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_policy_dsp.created_user
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    private Integer createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_policy_dsp.created_time
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_policy_dsp.updated_user
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    private Integer updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_sys_policy_dsp.updated_time
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy_dsp.id
     *
     * @return the value of mad_sys_policy_dsp.id
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy_dsp.id
     *
     * @param id the value for mad_sys_policy_dsp.id
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy_dsp.policy_id
     *
     * @return the value of mad_sys_policy_dsp.policy_id
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public Integer getPolicyId() {
        return policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy_dsp.policy_id
     *
     * @param policyId the value for mad_sys_policy_dsp.policy_id
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public void setPolicyId(Integer policyId) {
        this.policyId = policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy_dsp.dsp_id
     *
     * @return the value of mad_sys_policy_dsp.dsp_id
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public Integer getDspId() {
        return dspId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy_dsp.dsp_id
     *
     * @param dspId the value for mad_sys_policy_dsp.dsp_id
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public void setDspId(Integer dspId) {
        this.dspId = dspId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy_dsp.weight
     *
     * @return the value of mad_sys_policy_dsp.weight
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public Short getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy_dsp.weight
     *
     * @param weight the value for mad_sys_policy_dsp.weight
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public void setWeight(Short weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy_dsp.status
     *
     * @return the value of mad_sys_policy_dsp.status
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy_dsp.status
     *
     * @param status the value for mad_sys_policy_dsp.status
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy_dsp.created_user
     *
     * @return the value of mad_sys_policy_dsp.created_user
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy_dsp.created_user
     *
     * @param createdUser the value for mad_sys_policy_dsp.created_user
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy_dsp.created_time
     *
     * @return the value of mad_sys_policy_dsp.created_time
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy_dsp.created_time
     *
     * @param createdTime the value for mad_sys_policy_dsp.created_time
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy_dsp.updated_user
     *
     * @return the value of mad_sys_policy_dsp.updated_user
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy_dsp.updated_user
     *
     * @param updatedUser the value for mad_sys_policy_dsp.updated_user
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_sys_policy_dsp.updated_time
     *
     * @return the value of mad_sys_policy_dsp.updated_time
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_sys_policy_dsp.updated_time
     *
     * @param updatedTime the value for mad_sys_policy_dsp.updated_time
     *
     * @mbggenerated Wed Jul 19 17:15:49 CST 2017
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}