package com.madhouse.platform.premiummad.entity;

import java.util.Date;

public class ReportTask extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.id
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.type
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.start_date
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.end_date
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.report_uri
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private String reportUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.status
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.id
     *
     * @return the value of mad_report_task.id
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.id
     *
     * @param id the value for mad_report_task.id
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.type
     *
     * @return the value of mad_report_task.type
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.type
     *
     * @param type the value for mad_report_task.type
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.start_date
     *
     * @return the value of mad_report_task.start_date
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.start_date
     *
     * @param startDate the value for mad_report_task.start_date
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.end_date
     *
     * @return the value of mad_report_task.end_date
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.end_date
     *
     * @param endDate the value for mad_report_task.end_date
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.report_uri
     *
     * @return the value of mad_report_task.report_uri
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public String getReportUri() {
        return reportUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.report_uri
     *
     * @param reportUri the value for mad_report_task.report_uri
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setReportUri(String reportUri) {
        this.reportUri = reportUri == null ? null : reportUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.status
     *
     * @return the value of mad_report_task.status
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.status
     *
     * @param status the value for mad_report_task.status
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}