package com.madhouse.platform.premiummad.entity;

import java.util.Date;

public class SysMedia {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.id
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.name
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.type
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.category
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Byte category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.access_type
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Byte accessType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.api_type
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Byte apiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.advertiser_audit_mode
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Byte advertiserAuditMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.material_audit_mode
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Byte materialAuditMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.timeout
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Short timeout;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.status
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.description
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.created_user
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Integer createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.created_time
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.updated_user
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Integer updatedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mad_sys_media.updated_time
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	private Date updatedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.id
	 * @return  the value of mad_sys_media.id
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.id
	 * @param id  the value for mad_sys_media.id
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.name
	 * @return  the value of mad_sys_media.name
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.name
	 * @param name  the value for mad_sys_media.name
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.type
	 * @return  the value of mad_sys_media.type
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.type
	 * @param type  the value for mad_sys_media.type
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.category
	 * @return  the value of mad_sys_media.category
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Byte getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.category
	 * @param category  the value for mad_sys_media.category
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setCategory(Byte category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.access_type
	 * @return  the value of mad_sys_media.access_type
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Byte getAccessType() {
		return accessType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.access_type
	 * @param accessType  the value for mad_sys_media.access_type
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setAccessType(Byte accessType) {
		this.accessType = accessType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.api_type
	 * @return  the value of mad_sys_media.api_type
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Byte getApiType() {
		return apiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.api_type
	 * @param apiType  the value for mad_sys_media.api_type
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setApiType(Byte apiType) {
		this.apiType = apiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.advertiser_audit_mode
	 * @return  the value of mad_sys_media.advertiser_audit_mode
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Byte getAdvertiserAuditMode() {
		return advertiserAuditMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.advertiser_audit_mode
	 * @param advertiserAuditMode  the value for mad_sys_media.advertiser_audit_mode
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setAdvertiserAuditMode(Byte advertiserAuditMode) {
		this.advertiserAuditMode = advertiserAuditMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.material_audit_mode
	 * @return  the value of mad_sys_media.material_audit_mode
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Byte getMaterialAuditMode() {
		return materialAuditMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.material_audit_mode
	 * @param materialAuditMode  the value for mad_sys_media.material_audit_mode
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setMaterialAuditMode(Byte materialAuditMode) {
		this.materialAuditMode = materialAuditMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.timeout
	 * @return  the value of mad_sys_media.timeout
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Short getTimeout() {
		return timeout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.timeout
	 * @param timeout  the value for mad_sys_media.timeout
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setTimeout(Short timeout) {
		this.timeout = timeout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.status
	 * @return  the value of mad_sys_media.status
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.status
	 * @param status  the value for mad_sys_media.status
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.description
	 * @return  the value of mad_sys_media.description
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.description
	 * @param description  the value for mad_sys_media.description
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.created_user
	 * @return  the value of mad_sys_media.created_user
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Integer getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.created_user
	 * @param createdUser  the value for mad_sys_media.created_user
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setCreatedUser(Integer createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.created_time
	 * @return  the value of mad_sys_media.created_time
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.created_time
	 * @param createdTime  the value for mad_sys_media.created_time
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.updated_user
	 * @return  the value of mad_sys_media.updated_user
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Integer getUpdatedUser() {
		return updatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.updated_user
	 * @param updatedUser  the value for mad_sys_media.updated_user
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setUpdatedUser(Integer updatedUser) {
		this.updatedUser = updatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mad_sys_media.updated_time
	 * @return  the value of mad_sys_media.updated_time
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mad_sys_media.updated_time
	 * @param updatedTime  the value for mad_sys_media.updated_time
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}
}