package com.madhouse.platform.premiummad.dao;

import org.apache.ibatis.annotations.Param;

import com.madhouse.platform.premiummad.entity.AdspaceMappingDsp;

public interface AdspaceMappingDspMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_adspace_mapping_dsp
     *
     * @mbggenerated Fri Oct 20 10:27:59 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_adspace_mapping_dsp
     *
     * @mbggenerated Fri Oct 20 10:27:59 CST 2017
     */
    int insert(AdspaceMappingDsp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_adspace_mapping_dsp
     *
     * @mbggenerated Fri Oct 20 10:27:59 CST 2017
     */
    int insertSelective(AdspaceMappingDsp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_adspace_mapping_dsp
     *
     * @mbggenerated Fri Oct 20 10:27:59 CST 2017
     */
    AdspaceMappingDsp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_adspace_mapping_dsp
     *
     * @mbggenerated Fri Oct 20 10:27:59 CST 2017
     */
    int updateByPrimaryKeySelective(AdspaceMappingDsp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_adspace_mapping_dsp
     *
     * @mbggenerated Fri Oct 20 10:27:59 CST 2017
     */
    int updateByPrimaryKey(AdspaceMappingDsp record);
    
	/**
	 * 根据DSPID和SSP广告位ID获取DSP的广告位Key
	 * 
	 * @param adspaceId
	 * @param dspId
	 * @return
	 */
	AdspaceMappingDsp selectByAdspaceIdAndDspId(@Param("adspaceId") Integer adspaceId, @Param("dspId") Integer dspId);
}