package com.madhouse.platform.premiummad.dao;

import com.madhouse.platform.premiummad.entity.Advertiser;

public interface AdvertiserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int insert(Advertiser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int insertSelective(Advertiser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	Advertiser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Advertiser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int updateByPrimaryKey(Advertiser record);
}