package com.madhouse.platform.premiummad.dao;

import org.apache.ibatis.annotations.Param;
import com.madhouse.platform.premiummad.entity.AdvertiserUser;

public interface AdvertiserUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_advertiser_user
     *
     * @mbggenerated Thu Dec 14 10:41:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_advertiser_user
     *
     * @mbggenerated Thu Dec 14 10:41:49 CST 2017
     */
    int insert(AdvertiserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_advertiser_user
     *
     * @mbggenerated Thu Dec 14 10:41:49 CST 2017
     */
    int insertSelective(AdvertiserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_advertiser_user
     *
     * @mbggenerated Thu Dec 14 10:41:49 CST 2017
     */
    AdvertiserUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_advertiser_user
     *
     * @mbggenerated Thu Dec 14 10:41:49 CST 2017
     */
    int updateByPrimaryKeySelective(AdvertiserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_advertiser_user
     *
     * @mbggenerated Thu Dec 14 10:41:49 CST 2017
     */
    int updateByPrimaryKey(AdvertiserUser record);
    
	/**
	 * 根据广告主Id和用户Id获取绑定关系
	 * 
	 * @param advertiserId
	 * @param userId
	 * @return
	 */
    AdvertiserUser selectAdvertiserUser(@Param("advertiserId")Integer advertiserId, @Param("userId")String userId);
    
	/**
	 * 插入广告主和用户ID的绑定关系，返回主键
	 * 
	 * @param record
	 * @return
	 */
    int insertAdvertiserUser(AdvertiserUser record);
}