package com.madhouse.platform.premiummad.dao;

import java.util.List;

import com.madhouse.platform.premiummad.entity.AdvertiserMedia;
import com.madhouse.platform.premiummad.entity.AdvertiserMediaUnion;

public interface AdvertiserMediaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int insert(AdvertiserMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int insertSelective(AdvertiserMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	AdvertiserMedia selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int updateByPrimaryKeySelective(AdvertiserMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int updateByPrimaryKey(AdvertiserMedia record);
	
	/**
	 * 根据DSP定义的广告主ID获取审核结果
	 * @param advertiserKeys
	 * @return
	 */
	List<AdvertiserMediaUnion> selectAdvertiserMedias(String[] advertiserKeys);
}