package com.madhouse.platform.premiummad.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.madhouse.platform.premiummad.entity.AdvertiserMedia;
import com.madhouse.platform.premiummad.entity.AdvertiserMediaUnion;
import com.madhouse.platform.premiummad.model.AdvertiserMediaModel;

public interface AdvertiserMediaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Mon Jul 10 11:12:20 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Mon Jul 10 11:12:20 CST 2017
	 */
	int insert(AdvertiserMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Mon Jul 10 11:12:20 CST 2017
	 */
	int insertSelective(AdvertiserMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Mon Jul 10 11:12:20 CST 2017
	 */
	AdvertiserMedia selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Mon Jul 10 11:12:20 CST 2017
	 */
	int updateByPrimaryKeySelective(AdvertiserMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_advertiser_media
	 * @mbggenerated  Mon Jul 10 11:12:20 CST 2017
	 */
	int updateByPrimaryKey(AdvertiserMedia record);

	/**
	 * 根据DSP定义的广告主ID获取审核结果
	 * @param advertiserKeys
	 * @param dspId
	 * @return
	 */
	List<AdvertiserMediaUnion> selectAdvertiserMedias(@Param("advertiserKeys")String[] advertiserKeys, @Param("dspId")String dspId);
	
	/**
	 * 根据DSP定义的广告主ID和媒体ID列表查询广告主和媒体提交的记录
	 * @param param
	 * @return
	 */
	List<AdvertiserMediaUnion> selectByAdvertiserKeyAndMediaIds(AdvertiserMediaModel param);
	
	/**
	 * 批量插入
	 * @param list
	 * @return
	 */
	int insertByBatch(List<AdvertiserMedia> list);
	
	/**
	 * 批量更新
	 * @param list
	 * @return
	 */
	int updateByBath(List<AdvertiserMedia> list);
	
	/**
	 * 审核时更新相关信息
	 * @param record
	 * @return
	 */
	int updateForAudit(AdvertiserMedia record);
}