package com.madhouse.platform.premiummad.dao;

import java.util.List;

import com.madhouse.platform.premiummad.entity.DspMedia;

public interface DspMediaMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_dsp_media
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_dsp_media
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	int insert(DspMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_dsp_media
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	int insertSelective(DspMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_dsp_media
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	DspMedia selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_dsp_media
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	int updateByPrimaryKeySelective(DspMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_dsp_media
	 * @mbggenerated  Thu Dec 28 10:45:58 CST 2017
	 */
	int updateByPrimaryKey(DspMedia record);

	/**
     * 根据dspID查询
     * 
     * @param dspId
     * @return
     */
    List<DspMedia> selectByDspId(String dspId);
}