package com.madhouse.platform.premiummad.dao;

import java.util.List;
import com.madhouse.platform.premiummad.entity.MaterialMedia;
import com.madhouse.platform.premiummad.entity.MaterialMediaUnion;

public interface MaterialMediaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int insert(MaterialMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int insertSelective(MaterialMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	MaterialMedia selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int updateByPrimaryKeySelective(MaterialMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material_media
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int updateByPrimaryKey(MaterialMedia record);
	
	/**
	 * 根据DSP定义的素材ID获取审核结果
	 * @param materialKeys
	 * @return
	 */
	List<MaterialMediaUnion> selectAdvertiserMedias(String[] materialKeys);
}