package com.madhouse.platform.premiummad.dao;

import com.madhouse.platform.premiummad.entity.Material;

public interface MaterialMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int insert(Material record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int insertSelective(Material record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	Material selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Material record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_material
	 * @mbggenerated  Wed Jul 05 10:15:51 CST 2017
	 */
	int updateByPrimaryKey(Material record);
	
	/**
	 * 根据DSP提供的素材ID查询
	 * @param materialKey
	 * @return
	 */
	Material selectByMaterialKey(String materialKey);
	
	/**
	 * 插入素材信息，返回主键
	 * @param record
	 * @return
	 */
	int insertMaterial(Material record);
}