package com.madhouse.platform.premiummad.dao;

import com.madhouse.platform.premiummad.entity.PolicyAdspace;

public interface PolicyAdspaceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_policy_adspace
     *
     * @mbggenerated Wed Jul 19 17:12:16 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_policy_adspace
     *
     * @mbggenerated Wed Jul 19 17:12:16 CST 2017
     */
    int insert(PolicyAdspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_policy_adspace
     *
     * @mbggenerated Wed Jul 19 17:12:16 CST 2017
     */
    int insertSelective(PolicyAdspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_policy_adspace
     *
     * @mbggenerated Wed Jul 19 17:12:16 CST 2017
     */
    PolicyAdspace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_policy_adspace
     *
     * @mbggenerated Wed Jul 19 17:12:16 CST 2017
     */
    int updateByPrimaryKeySelective(PolicyAdspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mad_sys_policy_adspace
     *
     * @mbggenerated Wed Jul 19 17:12:16 CST 2017
     */
    int updateByPrimaryKey(PolicyAdspace record);
}