package com.madhouse.platform.premiummad.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.madhouse.platform.premiummad.entity.SysMedia;

public interface SysMediaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_media
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_media
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	int insert(SysMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_media
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	int insertSelective(SysMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_media
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	SysMedia selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_media
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	int updateByPrimaryKeySelective(SysMedia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mad_sys_media
	 * @mbggenerated  Mon Jul 10 10:17:53 CST 2017
	 */
	int updateByPrimaryKey(SysMedia record);
	
	/**
	 * 根据媒体ID查询
	 * @param idStrs
	 * @return
	 */
	public List<SysMedia> selectMedias(@Param("idStrs") String[] idStrs);
}