package com.madhouse.platform.premiummad.dto;

import java.util.Date;

public class ReportTaskDto {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.id
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.type
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.start_date
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.end_date
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.report_uri
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private String reportUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mad_report_task.status
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    private Short status;
    
    private Date createdTime;
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.id
     *
     * @return the value of mad_report_task.id
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.id
     *
     * @param id the value for mad_report_task.id
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.type
     *
     * @return the value of mad_report_task.type
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.type
     *
     * @param type the value for mad_report_task.type
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.report_uri
     *
     * @return the value of mad_report_task.report_uri
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public String getReportUri() {
        return reportUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.report_uri
     *
     * @param reportUri the value for mad_report_task.report_uri
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setReportUri(String reportUri) {
        this.reportUri = reportUri == null ? null : reportUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mad_report_task.status
     *
     * @return the value of mad_report_task.status
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mad_report_task.status
     *
     * @param status the value for mad_report_task.status
     *
     * @mbggenerated Tue Dec 05 17:53:38 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}
}
