package com.madhouse.platform.premiummad.media.tencent.constant;

/**
 * 常量
 */
public interface TencentConstant {
	Byte TENCENT_APP_STREAM_IMG = 1;
	Byte TENCENT_APP_STREAM_VIDEO = 2;
	Byte TENCENT_APP_STREAM_NATIVE = 3;
	Byte TENCENT_APP_STREAM_GIF = 4;
	Byte TENCENT_APP_STREAM_ICON = 5;
	Byte TENCENT_QQLIVE_APPWEB_VIDEO = 6;
	Byte TENCENT_QQLIVE_APPWEB_IMG = 7;
	Byte TENCENT_QQLIVE_APPWEB_PHONE_SPLASH_IMG = 8;
	Byte TENCENT_QQLIVE_APPWEB_PHONE_SPLASH_VIDEO = 9;
	Byte TENCENT_APP_KUAIBAO_SPLASH_IMG = 10;
	Byte TENCENT_APP_KUAIBAO_SPLASH_VIDEO = 11;
}
